### ISSUE TITLE
coh_tmm speedup?

### ISSUE THREAD

**Issue by toddkarin** [sbyrnes321/tmm#7]
I am trying to fit experimental reflection spectra with your package. It's working great, but is quite slow. It would be really great to speed up coh_tmm as much as possible. I only need `T` and `R` outputs. Is there a way to get a significant speedup here?

Also the reflection from the various interfaces is <5%. Is there a way to specify the number of internal reflections in the code?

**Comment by sbyrnes321** [comment]
The easiest way to speed it up would be numpy vectorization. But the code change is different depending on what variable you're vectorizing over (at least in many cases, and I think in this case). The second easiest way would be to switch to cython / c++ / julia / swift / whatever faster language you like, and use this code to occasionally double-check that you did it right. The algorithm isn't *that* complicated.

This package is designed for clarity and correctness, not speed. I find there's almost always a tradeoff (in Python at least). It's been a few years since I profiled, but last time I did, there wasn't a straightforward way to speed it up without making the code more complicated, in a way that made me concerned that I would introduce errors.

You can also see if [one of these](https://sjbyrnes.com/multilayer_film_optics_programs.html) works for you, and tell me if there's others I'm missing from that list.
